### ISSUE TITLE
Do something with words wrongly joined by commas

### ISSUE THREAD

**Issue by whoopsedesy** [sasansom/sedes#32]
In expectancy.all.csv, there are currently (85ba9e2a2b5e9fbf52655368451b6057922582a6) 31 cases where two or more words are joined by a comma (without whitespace), appearing as if a single lemma. You can find these in the file by searching for the `"` character.

We should cause words to be split if separated by punctuation, and/or fix the source texts to add missing whitespace.

```
$ grep '"' expectancy.all.csv
"ἀμφί,περίσκαίρω",1,1,NA,NA
"ἀμφί,περίστείνω",1,1,NA,NA
"ἀμφί,περίσφίγγω",1,1,NA,NA
"ἀνά,ἀπόλανθάνω",8,1,NA,NA
"ἀνά,ἀπόὕω",10,1,NA,NA
"ἀνά,ἐνῥιζόω",6.5,1,NA,NA
"ἀνά,ἐνῥοιζέω",6.5,1,NA,NA
"ἀντί,ἀνάδιδράσκω",1,1,NA,NA
"ἀντί,ἀνάδιδράσκω",5,1,NA,NA
"ἀντί,περίἠθέω",3,1,NA,NA
"ἀπό,εἰσσεύω",6.5,2,NA,NA
"ἀπό,πρόθρῴσκω",2.5,1,NA,NA
"ἐκ,ἀπόδιίημι",8,1,NA,NA
"ἐκ,ἐνἕπομαι",1,1,NA,NA
"ἐκ,ἐνἕπομαι",7,1,NA,NA
"ἐκ,ἐνἕπομαι",9,1,NA,NA
"ἐκ,ὑπόἀλύσσω",9,4,NA,NA
"ἐν,ἀντί,ἐνλούω",6.5,1,NA,NA
"ἐν,διάἀάω",1,1,NA,NA
"ἐν,ἐκλάζω",6.5,1,NA,NA
"ἐπί,ἐνῥιπίζω",6.5,1,NA,NA
"εἰς,ἀπόὕω",3,1,NA,NA
"κατά,ἐνἀντιάω",6,1,-1.4142135623731,-1
"κατά,ἐνἀντιάω",8,2,0.707106781186547,1
"κατά,ἐνῥιγέω",7,1,NA,NA
"κατά,εἰσσεύω",6.5,1,NA,NA
"μετά,εἰσσεύω",6.5,2,NA,NA
"παρά,ἐκνέομαι",6.5,3,NA,NA
"σύν,εἰσσεύω",6.5,1,NA,NA
"ὑπό,ἐκ,ἀπόὕω",2.5,1,NA,NA
"ὑπό,ἐκἀλέω",6.5,1,NA,NA
```

**Comment by whoopsedesy** [comment]
Cf. #20.

**Comment by sasansom** [comment]
It seems that all of these are in fact each single lemmata. They are compound words with more than one prefix, e.g.  ἀμφί,περίσκαίρω should be [ἀμφιπερισκαίρω](https://logeion.uchicago.edu/%E1%BC%80%CE%BC%CF%86%CE%B9%CF%80%CE%B5%CF%81%CE%B9%CF%83%CE%BA%CE%B1%CE%AF%CF%81%CF%89), "to skip all about," which is a combination of prepositions ἀμφί and περί with the verb σκαίρω. I'm unsure why the lemmatizer presents them this way. I'm pretty sure the statistics, however, are correct, since I bet they are mostly hapax legomena vel sim. and thus have NA z-scores.

**Comment by whoopsedesy** [comment]
You're right. I forgot that expectancy.all.csv contains lemmata, and not unlemmatized words. This is fine then.
