### ISSUE TITLE
Renumber short syllables and count from first syllable

### ISSUE THREAD

**Issue by whoopsedesy** [sasansom/sedes#5]
We should add .5 to the number of short feet, so that the first syllable to follow syllable 1 (say) is always numbered 2, regardless of whether it's a short or a long syllable. In other words, we are currently assigning position numbers as
```
+  -   -  +  -   -  +  -   -  +  -   -  +  -   -    +  +
1 1.5  2  3 3.5  4  5 5.5  6  7 7.5  8  9 9.5  10  11 12
```
It instead needs to be
```
+  -   -  +  -   -  +  -   -  +  -   -  +  -   -    +  +
1  2  2.5 3  4  4.5 5  6  6.5 7  8  8.5 9  10 10.5 11 12
```

We actually used to have it that way, but changed it in 6bb4b3609ac3b9a329f82080ec733396f644f042.

**Comment by whoopsedesy** [comment]
#6 is an attempt at implementing the new numbering. However I would like to add a few more test cases before merging it. Can you give me 4 or 5 lines and the sedes of each word in them?

Here are two specific cases for you to consider. The first one, Od. 1.1, changes the nominal sedes of three words, but it is a mere relabeling: the words remain in the same position in the sedes grid:

|word |before |after | changed? |
|:-------|:--------|:---------|:----:|
|ἄνδρα |1 |1 | |
|μοι |2 |2.5 | * |
|ἔννεπε |3 |3 | |
|μοῦσα |5 |5 | |
|πολύτροπον |6 |6.5 | * |
|ὃς |9 |9 | |
|μάλα |9.5 |10 | * |
|πολλὰ |11 |11 | |

```
before
1 1.5 2   3 3.5 4   5 5.5 6   7 7.5 8   9  9.5 10   11 12
ἄνδρα μοι ἔννεπε    μοῦσα πολύτροπον    ὃς μάλα     πολλὰ

after
1 2   2.5 3 4   4.5 5 6   6.5 7 8   8.5 9  10  10.5 11 12
ἄνδρα μοι ἔννεπε    μοῦσα πολύτροπον    ὃς μάλα     πολλὰ
```

A possibly more interesting case is Od. 345. Here, all the sedes are nominally the same, but because of the renumbering some words (*δ' αὖ* at sedes 2 and *πεπνυμένος* at sedes 6) actually appear in different places in the grid. See how *δ' αὖ* was formerly assigned to the second short syllable in the first foot, and now it goes to the first short syllable in the first foot.

|word |before |after | changed? |
|:-------|:--------|:---------|:----:|
|τὴν |1 |1 | |
|δ' αὖ |2 |2 | |
|Τηλέμαχος |3 |3 | |
|πεπνυμένος |6 |6 | |
|ἀντίον |9 |9 | |
|ηὔδα |11 |11 | |
```
before
1   1.5   2     3 3.5 4   5 5.5 6   7 7.5 8   9 9.5 10   11 12
τὴν       δ' αὖ Τηλέμαχος       πεπνυμένος    ἀντίον     ηὔδα

after
1   2     2.5   3 4   4.5 5 6   6.5 7 8   8.5 9 10  10.5 11 12
τὴν δ' αὖ       Τηλέμαχος   πεπνυμένος        ἀντίον     ηὔδα
```

Here are before-and-after renderings of Od. 1.345–359.
![before](https://user-images.githubusercontent.com/53617134/75749390-9bf03e00-5d19-11ea-9a08-dd398e2582cd.png)
![after](https://user-images.githubusercontent.com/53617134/75749399-a14d8880-5d19-11ea-95bc-7896600c7a2e.png)

**Comment by sasansom** [comment]
Here are five lines for which I've manually assigned _sedes_ to the words according to the revised schema (_Od_. 6.71-75, in which Nausikäa readies the wagon):

_Od_. 6.71
(ὣς, 1)
(εἰπὼν, 2) 
(δμώεσσιν, 4)
(ἐκέκλετο, 6.5)
(τοὶ, 9) 
(δ' ἐπίθοντο, 10)
6.72 
(οἱ, 1)
(μὲν, 2)
(ἄρ', 2.5)
(ἐκτὸς, 3)
(ἄμαξαν, 4.5) 
(ἐΰτροχον, 6.5)
(ἡμιονείην, 9)
6.73 
(ὅπλεον, 1)
(ἡμιόνους, 3)
(θ' ὕπαγον, 6)
(ζεῦξάν, 8)
(θ' ὑπ', 10)
(ἀπήνῃ, 10.5)
6.74 
(κούρη, 1)
(δ' ἐκ, 3)
(θαλάμοιο, 4)
(φέρεν, 6.5)
(ἐσθῆτα, 8)
(φαεινήν, 10.5)
6.75
(καὶ, 1)
(τὴν, 2)
(μὲν, 3)
(κατέθηκεν, 4)
(ἐϋξέστῳ, 6.5)
(ἐπ', 10)
(ἀπήνῃ, 10.5)

Great catch. I think the movement you observe in _sedes_ grid for the second example (_Od_. 1.345) confirms the benefits of the revised schema. In the _sedes_ grid, it makes sense for δ' αὖ to come right after τὴν, rather than being separated by a space for 1.5. Τὴν is only a single long syllable and should thus take up only one _sedes_ (1), not one and a half as implied by the old schema (1 and the space for 1.5). I think the movement reveals this conceptual error in the previous schema. The rived schema more accurately positions words in the _sedes_ grid.

This also clarifies something else: what the _sedes_ grid visualizes is the _sedes_ position for the first syllable of every word and the relative _sedes_ for each remaining syllable. The revised schema does this more accurately.

**Comment by whoopsedesy** [comment]
Thanks, the [additional test cases](https://github.com/sasansom/sedes/commit/3b91ab15398f1a2da553082ae7cf0702342fd185) check out.
