### ISSUE TITLE
Include Hellenistic, Imperial texts in corpus

### ISSUE THREAD

**Issue by sasansom** [sasansom/sedes#8]
Include the following Hellenistic texts in the corpus:

Apollonius of Rhodes, _Argonautica_:
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0227

Callimachus, _Hymns_ 1-4, 6:
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3atext%3a2008.01.0481%3ahymn%3d1
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3atext%3a2008.01.0481%3ahymn%3d2
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3atext%3a2008.01.0481%3ahymn%3d3
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3atext%3a2008.01.0481%3ahymn%3d4
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3atext%3a2008.01.0481%3ahymn%3d6

Theocritus, _Idylls_ 1-27
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D1
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D2
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D3
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D4
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D5
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D6
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D7
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D8
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D9
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D10
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D11
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D12
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D13
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D14
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D15
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D16
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D17
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D18
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D19
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D20
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D21
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D22
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D23
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D24
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D25
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D26
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0228%3Atext%3DId.%3Apoem%3D27

Aratus, _Phaenomena_:
http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0483

**Comment by sasansom** [comment]
XML (and json) texts here: https://github.com/cltk/greek_text_perseus

**Comment by sasansom** [comment]
If possible, I think we should add two imperial Greek epic texts, too:

Quintus of Smyrna, _Posthomerica_ (included in the XML/json texts above)
Nonnus of Panopolis, _Dionysiaca_: http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2008.01.0485

Some other scholars responding to O'Neill have done so, most recently [Bakker 2019](https://books.google.com/books?id=VjvEDwAAQBAJ&pg=PA79&lpg=PA79&dq=bakker+learning+the+epic+formula&source=bl&ots=6vk3aFr_kL&sig=ACfU3U3e6EaMxwoksqhsbGnJo1oqe-u3cQ&hl=en&ppis=_c&sa=X&ved=2ahUKEwiarNLk6ojoAhUETawKHd7JC-MQ6AEwAHoECDEQAQ#v=onepage&q=bakker%20learning%20the%20epic%20formula&f=false).

**Comment by whoopsedesy** [comment]
There's an XML download link at the bottom of the Perseus page. Don't use the more prominent orange "XML" buttons as those will only download a fragment.
![perseus-xml](https://user-images.githubusercontent.com/53617134/76493663-0f393480-642b-11ea-8651-332f8390d05c.png)

You can download the XML files and give them a sensible name under the corpus/ directory. Here's how everything else currently works around the corpus files. Let's say you've saved corpus/argonautica.xml. Now you need to add it to Makefile in two places
 * At the top, add it to the list of all known `WORKS`:
   ```
   WORKS = \
   	argonautica \
   	homerichymns \
    	iliad \
    	odyssey \
    	shield \
    	theogony \
    	worksanddays \
   ```
 * Then, assign it a short work identifier; here I've used `Argo.`:
   ```
   corpus/argonautica.csv:  WORK_IDENTIFIER = Argo.
   corpus/homerichymns.csv: WORK_IDENTIFIER = Hymns
   corpus/iliad.csv:        WORK_IDENTIFIER = Il.
   corpus/odyssey.csv:      WORK_IDENTIFIER = Od.
   corpus/shield.csv:       WORK_IDENTIFIER = Shield
   corpus/theogony.csv:     WORK_IDENTIFIER = Theog.
   corpus/worksanddays.csv: WORK_IDENTIFIER = WD
   ```

At this point, running `make` will attempt to process the file and create corpus/argonautica.csv, and a combined all.csv.

Unfortunately it's not that easy. The nature of Perseus TEI texts means that each new file is likely to require some TLC. If you try *Argonautica*, you'll get an error because it uses a slightly different XML format (lowercase `"book"` instead of `"Book"`). We can work around that of course, but the point is that there are likely to be many such things to deal with in each new text.
```
$ make
src/tei2csv "Argo." "corpus/argonautica.xml" > "corpus/argonautica.csv"
Traceback (most recent call last):
  File "src/tei2csv", line 80, in <module>
    process(f)
  File "src/tei2csv", line 45, in process
    for line in doc.lines():
  File "sedes/src/tei.py", line 189, in lines
    for x in do_elem(self.soup.find("text").body, Environment()):
  File "sedes/src/tei.py", line 168, in do_elem
    assert elem.get("type") in ("Book", "Hymn")
AssertionError
```

Maybe what would work best at this point is for you to download the XML files you want, with the filenames you want, and then only do the `WORK_IDENTIFIER` step of the two-step process above; that way they won't yet be processed, and I can deal with the format differences and enable them one by one.

It seems like it may make sense to have some finer categorization for comparison intra certains subsets of texts. For example we may have corpus/hellenistic/argonautica.xml instead of just corpus/argonautica.xml. That won't work directly with the system we have now, but we can make changes to accommodate it.
